export { default as Home } from './Home'
export { default as Routines } from './Routines'
export { default as MyRoutines } from './MyRoutines'
export { default as Activities } from './Activities'
export { default as Login } from './Login'
export { default as Signup } from './Signup'